spring:
  cloud:
    stream:
      bindings:
        consumer-in-0:
          destination: classicq-batch-topic
          group: test-group
          consumer:
            batch-mode: true
#            instance-count: 1
#            concurrency: 4
      rabbit:
        bindings:
          consumer-in-0:
            consumer:
              enable-batching: true
              batch-size: 10
              receive-timeout: 5000