server:
  port: 8081

spring:
  cloud:
    stream:
      function:
        definition: supplier
      bindings:
        supplier-out-0:
          destination: comm-topic-classic
      poller:
        fixed-delay: 500