server:
  port: 8081

spring:
  cloud:
    stream:
      function:
        definition: supplier
      bindings:
        supplier-out-0:
          destination: classicq-batch-topic
#          producer:
#            partition-key-expression: headers['partition_key']
#            partition-count: 4
      poller:
        fixed-delay: 500